$engine: 3
name: PlumeESXLegacy
version: 3.0.0
author: Tabarra & Chip
description: A full featured and highly configurable yet lightweight ESX Legacy base that can be easily extended. 

tasks:
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 0169fdddaa9511558cfa17bcf80a832f56c359ff
    subpath: resources
    dest: ./resources
  
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/tabarra/PlumeESX-recipe
    ref: main
    dest: ./tmp/plume_esx

  - action: move_path
    src: ./tmp/plume_esx/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/plume_esx/loadingscreen
    dest: ./resources/loadingscreen

  - action: connect_database
  - action: query_database
    file: ./tmp/plume_esx/plume.sql

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    ref: 50f8d23c6c7c20a420548728d962b741b2abc653
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/esx-framework/esx-legacy
    ref: d48f493e540b2909515a9603e4b569e7fe137f4d
    dest: ./resources/


  - action: download_github
    src: https://github.com/HypeLevels/simpledrift
    ref: 53b72cf605bd0ef82d71906245c3af0918187d13
    dest: ./resources/simpledrift

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: 4ae8aaefd38238e72ff8f36417decb05064cb924
    dest: ./resources/bob74_ipl
  

  ## KL HUD v2
  - action: download_github
    src: https://github.com/Kilichi/Kl_HudV2
    ref: ac8a321ff335706509bdc6122a2984a80082e669
    dest: ./resources/Kl_HudV2

  - action: replace_string
    file: ./resources/[esx]/esx_status/client/main.lua
    search: 'esx_status:onTick'
    replace: 'Kl_Hud:onTick'


  ## Final touches
  - action: replace_string
    mode: all_vars
    file: ./resources/loadingscreen/config.js
    
  - action: remove_path
    path: ./tmp

  - action: remove_path
    path: ./resources/esx_example

  - action: remove_path
    path: ./resources/server.cfg


